"""Initial schema with users, roads, routes, and favorites

Revision ID: c5794f3a76a7
Revises: 
Create Date: 2025-12-30 16:09:31.460442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'c5794f3a76a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('curvature', sa.Float(), nullable=False),
    sa.Column('length_meters', sa.Float(), nullable=False),
    sa.Column('surface', sa.String(length=50), nullable=True),
    sa.Column('join_type', sa.String(length=50), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', spatial_index=False), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    # Spatial index created automatically by GeoAlchemy2 from model's __table_args__
    sa.Index('idx_roads_geometry', 'geometry', postgresql_using='gist')
    )
    op.create_index(op.f('ix_roads_collection_id'), 'roads', ['collection_id'], unique=True)
    op.create_index(op.f('ix_roads_curvature'), 'roads', ['curvature'], unique=False)
    op.create_index(op.f('ix_roads_surface'), 'roads', ['surface'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('road_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    # Unique index created from model's __table_args__
    sa.Index('idx_user_favorites_unique', 'user_id', 'road_id', unique=True)
    )
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.create_table('user_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_distance_meters', sa.Float(), nullable=True),
    sa.Column('total_curvature', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_routes_user_id'), 'user_routes', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_table('route_roads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('road_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('connection_geometry', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', spatial_index=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['user_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    # Indexes created from model's __table_args__
    sa.Index('idx_route_roads_route_position', 'route_id', 'position'),
    sa.Index('idx_route_roads_connection_geometry', 'connection_geometry', postgresql_using='gist')
    )
    op.create_index(op.f('ix_route_roads_route_id'), 'route_roads', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_roads_route_id'), table_name='route_roads')
    op.drop_table('route_roads')  # Drops table and its __table_args__ indexes
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_routes_user_id'), table_name='user_routes')
    op.drop_table('user_routes')
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_table('user_favorites')  # Drops table and its __table_args__ indexes
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roads_surface'), table_name='roads')
    op.drop_index(op.f('ix_roads_curvature'), table_name='roads')
    op.drop_index(op.f('ix_roads_collection_id'), table_name='roads')
    op.drop_table('roads')  # Drops table and its __table_args__ indexes
    # ### end Alembic commands ###
